# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: karan5028ji.WinOptimizerPro
PackageVersion: 2.1.6
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - Win-Optimizer-Pro
ReleaseDate: 2026-10-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/karan5028ji/Win-Optimizer-Pro/releases/download/v2.1.6/Win-Optimizer-Pro_2.1.6_x64-setup.exe
    InstallerSha256: 769CCB0AC0AE1F53F2CFFC1DAA3AF78D1316E831016BF19515E629E4252465AB
ManifestType: installer
ManifestVersion: 1.12.0
